### ISSUE TITLE
wizard: pre-fill options with information from x-kusk extension

### ISSUE THREAD

**Issue by dobegor** [kubeshop/kusk-gen#80]

**Comment by kylehodgetts** [comment]
What should the behaviour be with this one? @dobegor @olensmar 

We populate the options with the settings in the extensions and then what do we do?

In my head there are 2 options:
A) Skip the questions for setting these in the wizard
B) Ask the questions anyway and use what's currently in the extension as the "default" and give the user a chance to override it?
